### PR TITLE
Feature/habitat service

### PR DESCRIPTION
**Pull request by bixu**
@maier, this is the (very rough!) PR I was talking about for getting the agent built as a Habitat service. You'd additionally want to wire it up to Builder to get builds propagating into the Builder artifact repository: https://www.habitat.sh/docs/using-builder/#automated-builds

### CODE REVIEW

**Comment by maier** [comment]
A couple things:

* Where is `default.toml` used? If it is intended to be the configuration file it would be better to use either the configuration file or the command line options. The command line options would override the configuration file. If it is not used, it might be better to not include it as it may become out of sync as the agent evolves. If it is used, set just the relevant options with a comment on using `--show-config=...` to see the full options available.
* The plugins, if they do not apply to all operating systems supported should not be put in the main plugins directory of the repository. They will get picked up and included in each release for all operating systems. Maybe put them in `habitat/plugins` and copy them into place from there.

**Comment by maier** [comment]
Ok. Yeah, I guess I'm missing something with regard to `default.toml`, which simply looks like the output of `circonus-agentd --show-config=toml`. How would a user change a setting in `default.toml` and have habitat tell the circonus-agent about the change? For example, how would a user enable statsd? It is disabled in the run command line via `--no-statsd` but in `default.toml` it is actually enabled.

If the settings in `default.toml` are actually something habitat is using and as the `cfg.*` expansions on the command line - all of the options should be exposed or habitat should be told to write that configuration out as a config file and then run `circonus-agentd --config=config_file` with no other options. In other words, drive all the options from the config file.

I'm concerned that mixing them may cause issues with someone changing something in `default.toml` but since there is already something overriding on the actual command line, their change appears to be ignored.

Since cosi isn't being used, adding alerting rules will need to be done with some quick and dirty utility or using curl commands. Or, waiting until the cosi-tool is done.

**Comment by bixu** [comment]
Ah yes - you are right about the mismatch in `default.toml` and the `run` hook. I was having some issues with Handlebars and was in a rush to get something that would work in a pinch for us internally at smartB, so I hardcoded some of that. Good catch, it needs to be fixed if the community is going to use it.

Going into Habitat internals a bit, there's some confusion here because you've got one of the few binaries out there that's modern enough to use TOML out-of-the-box. Habitat assumes that most apps are using a format harder to read, like JSON, and provides a tiny Handlebars abstraction layer to allow us to write TOML for clarity and template it into any config style we want. So it's really the Habitat Supervisor that's consuming `default.toml` here, not the agent directly. A good example for reference is the Habitat plan for Postgres (which has a bunch of config files with slightly idiosyncratic formatting and syntax).

TOML: https://github.com/habitat-sh/core-plans/blob/master/postgresql/default.toml
Config templates: https://github.com/habitat-sh/core-plans/tree/master/postgresql/config

**Comment by smartb-pair** [comment]
@maier, we've found a bug in config template rendering, so don't merge this until we update the PR with that fix.

**Comment by maier** [comment]
Ok, let me know when it is ready to merge. Glad you were able to run down that other issue to just a config change.

**Comment by bixu** [comment]
On vacation currently but will return to this when I get some free cycles at $job.

**Comment by bixu** [comment]
@maier, we just rebased the branch on master so this can be merged now. Merging the PR would allow us to automatically build the package and ship service updates.

**Comment by maier** [comment]
Can you fix the conflicts with .gitignore and then I'll merge the PR?

**Comment by bixu** [comment]
We found an issue which will require some refactoring. Will update the PR and fix the conflicts then.

Blake

**Comment by bixu** [comment]
@maier, the latest commits should put us in a good place. If you can point the public Habitat Builder at this repo (see https://www.habitat.sh/docs/using-builder/#automated-builds) we should get free builds and artifacts in the public repo for the Agent. I suppose you could also claim the `circonus` origin in Builder since I think that name is still available.

**Pull request merged**
